insert into City
    (CityName, CountryID)
values 
    ('Fort Worth',4),
    ('Kansas City',3),
    ('Charlotte',3),
    ('Muskegon',1),
    ('Orlando',1),
    ('Marietta',1),
    ('Washington',2),
    ('Los Angeles',1),
    ('Kansas City',3),
    ('Colorado Springs',3),
    ('Sacramento',3),
    ('Otorohanga',1),
    ('Humble',4),
    ('Denver',2),
    ('Louisville',1),
    ('El Paso',3),
    ('Los Angeles',4),
    ('Amarillo',3),
    ('Fort Worth',4),
    ('Elmira',1),
    ('Madison',3),
    ('Cincinnati',1),
    ('Tucson',4),
    ('Louisville',1),
    ('Jackson',2),
    ('Evansville',4),
    ('Miami',3),
    ('Omaha',4),
    ('Cumming',4),
    ('Hagerstown',1),
    ('Birmingham',2),
    ('Taipa',2),
    ('Knoxville',3),
    ('Lexington',1),
    ('Colorado Springs',4),
    ('Salt Lake City',4),
    ('Anchorage',4),
    ('Fresno',4),
    ('Washington',2),
    ('Minneapolis',3),
    ('Chattanooga',3),
    ('Charleston',3),
    ('Montgomery',4),
    ('New Orleans',4),
    ('Saint Paul',2),
    ('Brampton',4),
    ('Upton',4),
    ('Tulsa',1),
    ('Des Moines',1),
    ('Little Rock',2),
    ('Atlanta',3),
    ('Tulsa',1),
    ('Savannah',2),
    ('Lincoln',3),
    ('Oakland',3),
    ('Springfield',4),
    ('Burnside',4),
    ('Des Moines',4),
    ('Seattle',1),
    ('Newport',4),
    ('San Diego',1),
    ('Fort Wayne',3),
    ('Minneapolis',3),
    ('New Orleans',1),
    ('Evansville',4),
    ('Atlanta',1),
    ('Wakefield',4),
    ('Simi Valley',2),
    ('Houston',1),
    ('Durham',4),
    ('Savannah',1),
    ('Largo',4),
    ('Sacramento',4),
    ('Long Beach',2),
    ('Virginia Beach',4),
    ('Houston',2),
    ('Vienna',1),
    ('Irving',3),
    ('Gore',4),
    ('Huntington',4),
    ('Detroit',3),
    ('Red Hill',2),
    ('Ogden',1),
    ('Tullich',4),
    ('Baltimore',3),
    ('Winston Salem',4),
    ('Bradenton',4),
    ('West End',4),
    ('Clearwater',2),
    ('Fort Worth',4),
    ('Chicago',4),
    ('Irving',3),
    ('London',3),
    ('Alhambra',2),
    ('Vienna',3),
    ('Philadelphia',3),
    ('Sydney',3),
    ('Huntington',1),
    ('Las Vegas',1),
    ('Richmond',3),
    ('Seaton',4),
    ('Milton',4),
    ('Moerewa',3),
    ('Tamaki',4),
    ('Norton',2),
    ('Newton',1),
    ('Rosebank',3),
    ('Adelaide Mail Centre',2),
    ('Kerikeri',4),
    ('Kinloch',3),
    ('Methven',3),
    ('Sydney',1),
    ('Foxton',4),
    ('Otorohanga',2),
    ('Pukekohe East',3),
    ('Levin',2),
    ('Upton',4),
    ('Marston',2),
    ('Upton',1),
    ('Hobart',2),
    ('Waitangi',4),
    ('Sydney',3),
    ('Edinburgh',3),
    ('Melbourne',3),
    ('Kerikeri',1),
    ('Buckland',2),
    ('North Shore',3),
    ('Hastings',1),
    ('Kawerau',3),
    ('London',4),
    ('Bulls',1),
    ('Levin',4),
    ('North Shore',1),
    ('Kawakawa',3),
    ('Paraparaumu',3),
    ('Weston',2),
    ('Tamaki',2),
    ('Taradale',4),
    ('Paihia',4),
    ('Sheffield',2),
    ('Red Hill',1),
    ('Otorohanga',1),
    ('Manukau City',2),
    ('Melbourne',2),
    ('Turangi',3),
    ('Melbourne',3),
    ('Sydney',3),
    ('Sydney',4),
    ('Brisbane',1),
    ('Raglan',1),
    ('Milton',4),
    ('Sydney',3),
    ('Manchester',1),
    ('Eastern Suburbs Mc',3),
    ('Thames',1),
    ('Carlton',2),
    ('Sheffield',2),
    ('Sydney',1),
    ('Porirua',1),
    ('Sydney',2),
    ('Waihi',3),
    ('Perth',1),
    ('Seaton',2),
    ('Raglan',3),
    ('Gore',1),
    ('Marston',3),
    ('Whakatane',2),
    ('Lower Hutt',3),
    ('Patea',3),
    ('Melbourne',1),
    ('Hastings',1),
    ('Wirral',1),
    ('Sydney',4),
    ('Otorohanga',3),
    ('Horton',2),
    ('Kirkton',3),
    ('Bluff',4),
    ('Sydney',3),
    ('Kaiapoi',1),
    ('Church End',4),
    ('Norton',3),
    ('Launceston',1),
    ('Waihi',4),
    ('East End',4),
    ('Upton',1),
    ('Norton',2),
    ('Sydney',2),
    ('Melbourne',3),
    ('Turangi',4),
    ('Richmond',1),
    ('Lower Hutt',1),
    ('Timaru',1),
    ('Newton',3),
    ('Hobart',3),
    ('Brooklyn',3),
    ('Newbiggin',2),
    ('Eastern Suburbs Mc',4),
    ('Adelaide Mail Centre',2),
    ('Norton',1),
    ('Wakefield',1);
